#
# Awesome App Landing Page Config
#

# Be sure all REQUIRED fields are filled out!

#
# General App Info
#
app:
  name: xClaim - Identity Wallet # REQUIRED - Enter your app name
  ios_id: 1288339409 # REQUIRED - 10 Digit Numeric App ID (lookup in iTunes Connect)
  android_id: com.wallet.crypto.trustapp
  icon: images/app-icon-512.png
  screenshot: images/app-screen-640x1136.png

#
# Marketing
#
marketing_header: # Optional
marketing_desc: xClaim - Identity claims and fast and secure Ethereum ERC20 Compatible wallet.

#
# Social Links
#
# Includes an icon for each username you enter
#
social-links:
  github: xclaim
  reddit:
  medium:
  facebook:
  twitter:
  pinterest:
  instagram:
  email: info@carechain.io
  youtube: # channel/<your_long_string> or <user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/

#
# Enable/Disable Features & Page Elements
#
enable:
  app_icon: true
  smart_app_banner: true

#
# Device
#
# Available devices:
# * iphone-se-silver-vertical
# * iphone-se-space-gray-vertical
# * ipod-touch-blue-vertical
#
device: iphone-se-silver-vertical # REQUIRED

#
# Theme Settings
#
background_color: "#2e91db" # Optional
background_image: # Optional - Use Relative path e.g. images/backgrounds/image.jpg
text_color: white # Optional
link_color: # Optional
social_link_color: white # Optional
download_button_background_color: "#0191FF" # Optional
download_button_text_color: white; # Optional

#
# Site Info
#
# If you want specific meta info for your <head></head> tags
#
title: xClaim - Identity Wallet # Optional - Enter your site title
description: xClaim - Self-Sovereign Identity and Ethereum wallet that’s easy to use. # Optional - Enter your site description

#
# Google Analytics
#
google_analytics: UA-111751338-1 # Enter your tracking code (e.g. UA-2110908-2) to activate tracking

#
# iTunes Affiliate Program
#
# Sign up here: http://www.apple.com/itunes/affiliates/
#
# Disclaimer:
# This will default to using the author's affiliate token if left blank
#
itunes_affiliate_token: # Optional

#
# !! You don't need to change any of the configuration flags below !!
#

# The release of Awesome App Landing Page that you're using
version: v1.0

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
